// action - customization reducer
export const SET_MENU = '@customization/SET_MENU';
export const MENU_TOGGLE = '@customization/MENU_TOGGLE';
export const MENU_OPEN = '@customization/MENU_OPEN';
export const SET_FONT_FAMILY = '@customization/SET_FONT_FAMILY';
export const SET_BORDER_RADIUS = '@customization/SET_BORDER_RADIUS';
export const OPEN_MODAL = '@modal/OPEN_MODAL';
export const CLOSE_MODAL = '@modal/CLOSE_MODAL';
export const PARSE_DATA = '@peoples/PARSE_DATA';
export const DELETE_ALL_DATA = '@peoples/DELETE_ALL_DATA';
export const LOAD_DATA = '@peoples/LOAD_DATA';
